from microsoft:sdk as build-env
workdir /app

# copy csproj and restore as distint layers
copy webapp/* .csproj ./
run dotnet restore

# copy everything else and build
copy ./webapp ./
run dotnet publish -c Realese -o out

# build runtime image
from microsoft/dotnet:aspnetcore-runtime
workdir /app
copy --from=build-env /app/out .
entrypoint ["dotnet", "webapp.dll"]
